FROM alpine:latest

RUN apk update && \
    apk add --no-cache git bash dcron curl && \
    apk add git-lfs && \
    git lfs install

RUN echo "*/45 * * * * /backup/backup.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/root

USER root
CMD ["crond", "-f"]